AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with static website hosting and CloudFront distribution

Resources:
  WebsiteS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: hw-10
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  WebsiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::hw-10/*'

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteS3Bucket.WebsiteURL
            Id: WebsiteS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: WebsiteS3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  WebsiteURL:
    Description: "S3 Bucket URL"
    Value: !GetAtt WebsiteS3Bucket.WebsiteURL

  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !GetAtt CloudFrontDistribution.DomainName
